/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Igra;
import nitiK.NitK;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;
/**
 *
 * @author milos
 */
public class KlijentskaForma extends javax.swing.JFrame {

    
    private int brojac=0;
    private List<Igra>pokusaji=new ArrayList<>();
    /**
     * Creates new form KlijentskaForma
     */
    private NitK nit1;
    private NitK nit2;
    private NitK nit3;
    private NitK nit4;
    public KlijentskaForma() {
        initComponents();
        ModelTabelePokusaji mtp=new ModelTabelePokusaji(pokusaji);
        jTablePokusaji.setModel(mtp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelcifra1 = new javax.swing.JLabel();
        jLabelcifra2 = new javax.swing.JLabel();
        jLabelcifra3 = new javax.swing.JLabel();
        jLabelcifra4 = new javax.swing.JLabel();
        jButtonStart1 = new javax.swing.JButton();
        jButtonStart2 = new javax.swing.JButton();
        jButtonStart3 = new javax.swing.JButton();
        jButtonStart4 = new javax.swing.JButton();
        jButtonStop1 = new javax.swing.JButton();
        jButtonStop2 = new javax.swing.JButton();
        jButtonStop3 = new javax.swing.JButton();
        jButtonStop4 = new javax.swing.JButton();
        jButtonPosalji = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNaMestu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldVanMesta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePokusaji = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelcifra1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelcifra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcifra1.setText("0");

        jLabelcifra2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelcifra2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcifra2.setText("0");

        jLabelcifra3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelcifra3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcifra3.setText("0");

        jLabelcifra4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelcifra4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcifra4.setText("0");

        jButtonStart1.setText("Start-1");
        jButtonStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart1ActionPerformed(evt);
            }
        });

        jButtonStart2.setText("Start-2");
        jButtonStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart2ActionPerformed(evt);
            }
        });

        jButtonStart3.setText("Start-3");
        jButtonStart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart3ActionPerformed(evt);
            }
        });

        jButtonStart4.setText("Start-4");
        jButtonStart4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart4ActionPerformed(evt);
            }
        });

        jButtonStop1.setText("Stop-1");
        jButtonStop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStop1ActionPerformed(evt);
            }
        });

        jButtonStop2.setText("Stop-2");
        jButtonStop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStop2ActionPerformed(evt);
            }
        });

        jButtonStop3.setText("Stop-3");
        jButtonStop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStop3ActionPerformed(evt);
            }
        });

        jButtonStop4.setText("Stop-4");
        jButtonStop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStop4ActionPerformed(evt);
            }
        });

        jButtonPosalji.setText("Posalji");
        jButtonPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosaljiActionPerformed(evt);
            }
        });

        jLabel5.setText("Broj pogodjenih cifara koje jesu na svom mestu:");

        jLabel6.setText("Broj pogodjenih cifara koje nisu na svom mestu:");

        jTablePokusaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePokusaji);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelcifra1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPosalji)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonStop1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonStop2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonStop3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonStop4))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldVanMesta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                                .addComponent(jTextFieldNaMestu, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonStart1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonStart2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabelcifra2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonStart3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabelcifra3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonStart4)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabelcifra4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStart1)
                    .addComponent(jButtonStart2)
                    .addComponent(jButtonStart3)
                    .addComponent(jButtonStart4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelcifra1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelcifra2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelcifra3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelcifra4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButtonPosalji)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStop1)
                    .addComponent(jButtonStop2)
                    .addComponent(jButtonStop3)
                    .addComponent(jButtonStop4))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNaMestu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldVanMesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart1ActionPerformed
        nit1=new NitK(this, jLabelcifra1);
        nit1.start();
    }//GEN-LAST:event_jButtonStart1ActionPerformed

    private void jButtonStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart2ActionPerformed
        nit2=new NitK(this, jLabelcifra2);
        nit2.start();
    }//GEN-LAST:event_jButtonStart2ActionPerformed

    private void jButtonStart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart3ActionPerformed
        nit3=new NitK(this, jLabelcifra3);
        nit3.start();
    }//GEN-LAST:event_jButtonStart3ActionPerformed

    private void jButtonStart4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart4ActionPerformed
        nit4=new NitK(this, jLabelcifra4);
        nit4.start();
    }//GEN-LAST:event_jButtonStart4ActionPerformed

    private void jButtonStop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStop1ActionPerformed
        nit1.zaustavi();
    }//GEN-LAST:event_jButtonStop1ActionPerformed

    private void jButtonStop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStop2ActionPerformed
        nit2.zaustavi();
    }//GEN-LAST:event_jButtonStop2ActionPerformed

    private void jButtonStop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStop3ActionPerformed
        nit3.zaustavi();
    }//GEN-LAST:event_jButtonStop3ActionPerformed

    private void jButtonStop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStop4ActionPerformed
        nit4.zaustavi();
    }//GEN-LAST:event_jButtonStop4ActionPerformed

    private void jButtonPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosaljiActionPerformed
        String kombinacija=jLabelcifra1.getText()+"-"+jLabelcifra2.getText()+"-"+jLabelcifra3.getText()+"-"+jLabelcifra4.getText();
        brojac++;
        Igra pokusaj=new Igra(brojac, kombinacija, 5, 5);
        KlijentskiZahtev kz=new KlijentskiZahtev(operacije.Operacije.vratiBrojPogodjenih, pokusaj);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        
        pokusaj=(Igra) komunikacija.Komunikacija.getInstance().primiOdgovor().getServerskiOdgovor();
        System.out.println(pokusaj);
        pokusaji.add(pokusaj);
        
        ModelTabelePokusaji mtp=new ModelTabelePokusaji(pokusaji);
        jTablePokusaji.setModel(mtp);
        
        if(pokusaj.getBrojPogodjenihNaMestu()==4){
            JOptionPane.showMessageDialog(this, "Uspeh!");
            jButtonPosalji.setEnabled(false);
            brojac=0;
        }else if(brojac>=6){
            JOptionPane.showMessageDialog(this, "Nemas vise pokusaja!");
            jButtonPosalji.setEnabled(false);
            brojac=0;
        }
        
        jTextFieldNaMestu.setText(pokusaj.getBrojPogodjenihNaMestu()+"");
        jTextFieldVanMesta.setText(pokusaj.getBrojPogodjenihVanMesta()+"");
    }//GEN-LAST:event_jButtonPosaljiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPosalji;
    private javax.swing.JButton jButtonStart1;
    private javax.swing.JButton jButtonStart2;
    private javax.swing.JButton jButtonStart3;
    private javax.swing.JButton jButtonStart4;
    private javax.swing.JButton jButtonStop1;
    private javax.swing.JButton jButtonStop2;
    private javax.swing.JButton jButtonStop3;
    private javax.swing.JButton jButtonStop4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelcifra1;
    private javax.swing.JLabel jLabelcifra2;
    private javax.swing.JLabel jLabelcifra3;
    private javax.swing.JLabel jLabelcifra4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePokusaji;
    private javax.swing.JTextField jTextFieldNaMestu;
    private javax.swing.JTextField jTextFieldVanMesta;
    // End of variables declaration//GEN-END:variables

//    public void popunilabelu(JLabel labela) {
//        Random r=new Random();
//        int min=0;
//        int max=5;
//        int broj=r.nextInt(max-min+1)+min;
//        if(jLabelcifra1.equals(labela)){
//            jLabelcifra1.setText(String.valueOf(broj));
//        }else if(labela.equals(jLabelcifra2)){
//            jLabelcifra2.setText(String.valueOf(broj));
//        }else if(labela.equals(jLabelcifra3)){
//            jLabelcifra3.setText(String.valueOf(broj));
//        }else if(labela.equals(jLabelcifra4)){
//            jLabelcifra4.setText(String.valueOf(broj));
//        }
//        
//    }
}
